In [1]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

print(torch.__version__)
print(device)

2.1.1+cu121
cuda


### Scalar

In [3]:
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())

tensor(7)
0
7


### Vector

In [4]:
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)
print(vector[0])

tensor([7, 7])
1
torch.Size([2])
tensor(7)


### Matrix

In [5]:
MATRIX = torch.tensor([
    [7,  8],
    [9, 10]
])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[0])

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])
tensor([7, 8])


### Tensor

In [6]:
TENSOR = torch.tensor([
    [
        [1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]
    ]
])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0])

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])


### Random Tensors

In [7]:
random_tensor = torch.rand(size=(3, 4))
print(random_tensor)
print(random_tensor.dtype)

tensor([[0.5786, 0.6175, 0.5053, 0.8176],
        [0.4118, 0.2686, 0.8314, 0.6451],
        [0.8709, 0.6384, 0.0048, 0.9098]])
torch.float32


### Initialize with Zeros

In [8]:
zeros = torch.zeros(size=(3, 4))
print(zeros)
print(zeros.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32


### Initialize with Ones

In [9]:
ones = torch.ones(size=(3, 4))
print(ones)
print(ones.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


### Initialize with Range

In [10]:
zero_to_ten = torch.arange(start=0, end=11, step=1)
print(zero_to_ten)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


### Specific Tensors

In [11]:
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None, #defaults to torch.float32
    device=None, #defaults to CPU
    requires_grad=False, #if true, operations performed on the tensor are saved
)
print(float_32_tensor.shape)
print(float_32_tensor.dtype)
print(float_32_tensor.device)

float_16_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=torch.float16 #or torch.half
)
print(float_16_tensor.dtype)

torch.Size([3])
torch.float32
cpu
torch.float16


### Similar Tensors

In [12]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
print(ten_zeros)

float_16_tensor = float_32_tensor.type(torch.float16)
print(float_16_tensor)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([3., 6., 9.], dtype=torch.float16)


### Basic Operations

In [13]:
tensor = torch.tensor([1, 2, 3])

# Addition
print(tensor + 10)

# Subtraction
print(tensor - 10)

# Element Multiplication
print(tensor * 10)

# Matrix Multiplication
print(torch.matmul(tensor, tensor))

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor(14)


# Tensor View

In [14]:
tensor = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
reshapedTensor = tensor.view((4, 2))
print(reshapedTensor)
print(tensor)
tensor.permute((1, 0))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])

# Tensor Reshaping

In [15]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

# Random Reproucibility

In [16]:
torch.manual_seed(42)
random_tensor1 = torch.rand(3, 4)
torch.manual_seed(42)
random_tensor2 = torch.rand(3, 4)
random_tensor1, random_tensor2

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

# Current GPU

In [17]:
!nvidia-smi

Sat Dec  2 23:57:32 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.79                 Driver Version: 531.79       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1660 Ti    WDDM | 00000000:08:00.0  On |                  N/A |
| 42%   41C    P0               21W / 120W|   2496MiB /  6144MiB |      2%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

# If PyTorch can use GPU

In [18]:
torch.cuda.is_available(), torch.cuda.device_count()

(True, 1)

# Move Tensors from CPU to GPU

In [19]:
tensor = torch.tensor([1, 2, 3])
print(tensor.device)

tensorOnGPU = tensor.to('cuda:0')
print(tensorOnGPU.device)

tensorOnCPU = tensorOnGPU.cpu()
print(tensorOnCPU.device)

cpu
cuda:0
cpu


# Exercises

In [27]:
import torch

torch.manual_seed(0)
X = torch.rand(size=(7, 7))
X 

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [39]:
torch.manual_seed(0)
Y = torch.rand(1, 7)

torch.matmul(X, Y.T)

tensor([[1.1173],
        [1.7231],
        [1.4061],
        [1.9499],
        [0.9564],
        [1.3146],
        [1.1037]])

In [40]:
torch.cuda.manual_seed(1234)

In [44]:
torch.manual_seed(1234)
gpuX = torch.rand(size=(2, 3)).to("cuda")
# torch.manual_seed(1234)
gpuY = torch.rand(size=(2, 3)).to("cuda")

result = torch.matmul(gpuX, gpuY.T)
result

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [45]:
result.max(), result.min()

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

In [46]:
result.argmax(), result.argmin()

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

In [47]:
tensor = torch.rand(size=(1, 1, 1, 10))
newTensor = tensor.squeeze()

tensor, newTensor

(tensor([[[[0.7749, 0.8208, 0.2793, 0.6817, 0.2837, 0.6567, 0.2388, 0.7313,
            0.6012, 0.3043]]]]),
 tensor([0.7749, 0.8208, 0.2793, 0.6817, 0.2837, 0.6567, 0.2388, 0.7313, 0.6012,
         0.3043]))