In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.1


### Scalar

In [2]:
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())

tensor(7)
0
7


### Vector

In [ ]:
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)
print(vector[0])

### Matrix

In [3]:
MATRIX = torch.tensor([
    [7,  8],
    [9, 10]
])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[0])

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])
tensor([7, 8])


### Tensor

In [ ]:
TENSOR = torch.tensor([
    [
        [1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]
    ]
])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0])

### Random Tensors

In [ ]:
random_tensor = torch.rand(size=(3, 4))
print(random_tensor)
print(random_tensor.dtype)

### Initialize with Zeros

In [ ]:
zeros = torch.zeros(size=(3, 4))
print(zeros)
print(zeros.dtype)

### Initialize with Ones

In [ ]:
ones = torch.ones(size=(3, 4))
print(ones)
print(ones.dtype)

### Initialize with Range

In [ ]:
zero_to_ten = torch.arange(start=0, end=11, step=1)
print(zero_to_ten)

### Specific Tensors

In [ ]:
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None, #defaults to torch.float32
    device=None, #defaults to CPU
    requires_grad=False, #if true, operations performed on the tensor are saved
)
print(float_32_tensor.shape)
print(float_32_tensor.dtype)
print(float_32_tensor.device)

float_16_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=torch.float16 #or torch.half
)
print(float_16_tensor.dtype)

### Similar Tensors

In [ ]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
print(ten_zeros)

float_16_tensor = float_32_tensor.type(torch.float16)
print(float_16_tensor)

### Basic Operations

In [4]:
tensor = torch.tensor([1, 2, 3])

# Addition
print(tensor + 10)

# Subtraction
print(tensor - 10)

# Element Multiplication
print(tensor * 10)

# Matrix Multiplication
print(torch.matmul(tensor, tensor))

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor(14)


In [7]:
tensor = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
reshapedTensor = tensor.view((4, 2))
print(reshapedTensor)
print(tensor)
tensor.permute((1, 0))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])

In [8]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [3]:
torch.manual_seed(42)
random_tensor1 = torch.rand(3, 4)
torch.manual_seed(42)
random_tensor2 = torch.rand(3, 4)
random_tensor1, random_tensor2

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

In [4]:
!nvidia-smi

zsh:1: command not found: nvidia-smi
